# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import parser_pb2 as parser__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in parser_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ParserServiceStub(object):
    """Dictionary parsing service interface
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseDictionary = channel.unary_unary(
                '/langviz.parser.ParserService/ParseDictionary',
                request_serializer=parser__pb2.ParseRequest.SerializeToString,
                response_deserializer=parser__pb2.ParseResponse.FromString,
                _registered_method=True)
        self.NormalizeText = channel.unary_unary(
                '/langviz.parser.ParserService/NormalizeText',
                request_serializer=parser__pb2.NormalizeRequest.SerializeToString,
                response_deserializer=parser__pb2.NormalizeResponse.FromString,
                _registered_method=True)
        self.ExtractIPA = channel.unary_unary(
                '/langviz.parser.ParserService/ExtractIPA',
                request_serializer=parser__pb2.ExtractIPARequest.SerializeToString,
                response_deserializer=parser__pb2.ExtractIPAResponse.FromString,
                _registered_method=True)


class ParserServiceServicer(object):
    """Dictionary parsing service interface
    """

    def ParseDictionary(self, request, context):
        """Parse dictionary file to normalized entries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NormalizeText(self, request, context):
        """Normalize text using Perl regex engine
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractIPA(self, request, context):
        """Extract IPA from various notation systems
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseDictionary': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseDictionary,
                    request_deserializer=parser__pb2.ParseRequest.FromString,
                    response_serializer=parser__pb2.ParseResponse.SerializeToString,
            ),
            'NormalizeText': grpc.unary_unary_rpc_method_handler(
                    servicer.NormalizeText,
                    request_deserializer=parser__pb2.NormalizeRequest.FromString,
                    response_serializer=parser__pb2.NormalizeResponse.SerializeToString,
            ),
            'ExtractIPA': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractIPA,
                    request_deserializer=parser__pb2.ExtractIPARequest.FromString,
                    response_serializer=parser__pb2.ExtractIPAResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'langviz.parser.ParserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('langviz.parser.ParserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ParserService(object):
    """Dictionary parsing service interface
    """

    @staticmethod
    def ParseDictionary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/langviz.parser.ParserService/ParseDictionary',
            parser__pb2.ParseRequest.SerializeToString,
            parser__pb2.ParseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NormalizeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/langviz.parser.ParserService/NormalizeText',
            parser__pb2.NormalizeRequest.SerializeToString,
            parser__pb2.NormalizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractIPA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/langviz.parser.ParserService/ExtractIPA',
            parser__pb2.ExtractIPARequest.SerializeToString,
            parser__pb2.ExtractIPAResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
