# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: parser.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'parser.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cparser.proto\x12\x0elangviz.parser\"0\n\x0cParseRequest\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\"_\n\rParseResponse\x12&\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x15.langviz.parser.Entry\x12\x14\n\x0ctotal_parsed\x18\x02 \x01(\x05\x12\x10\n\x08warnings\x18\x03 \x03(\t\"\x94\x01\n\x05\x45ntry\x12\x10\n\x08headword\x18\x01 \x01(\t\x12\x0b\n\x03ipa\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x12\n\ndefinition\x18\x04 \x01(\t\x12\x16\n\tetymology\x18\x05 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07pos_tag\x18\x06 \x01(\tH\x01\x88\x01\x01\x42\x0c\n\n_etymologyB\n\n\x08_pos_tag\"4\n\x10NormalizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\noperations\x18\x02 \x03(\t\"\'\n\x11NormalizeResponse\x12\x12\n\nnormalized\x18\x01 \x01(\t\"3\n\x11\x45xtractIPARequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08notation\x18\x02 \x01(\t\"2\n\x12\x45xtractIPAResponse\x12\x0b\n\x03ipa\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\x8a\x02\n\rParserService\x12N\n\x0fParseDictionary\x12\x1c.langviz.parser.ParseRequest\x1a\x1d.langviz.parser.ParseResponse\x12T\n\rNormalizeText\x12 .langviz.parser.NormalizeRequest\x1a!.langviz.parser.NormalizeResponse\x12S\n\nExtractIPA\x12!.langviz.parser.ExtractIPARequest\x1a\".langviz.parser.ExtractIPAResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'parser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARSEREQUEST']._serialized_start=32
  _globals['_PARSEREQUEST']._serialized_end=80
  _globals['_PARSERESPONSE']._serialized_start=82
  _globals['_PARSERESPONSE']._serialized_end=177
  _globals['_ENTRY']._serialized_start=180
  _globals['_ENTRY']._serialized_end=328
  _globals['_NORMALIZEREQUEST']._serialized_start=330
  _globals['_NORMALIZEREQUEST']._serialized_end=382
  _globals['_NORMALIZERESPONSE']._serialized_start=384
  _globals['_NORMALIZERESPONSE']._serialized_end=423
  _globals['_EXTRACTIPAREQUEST']._serialized_start=425
  _globals['_EXTRACTIPAREQUEST']._serialized_end=476
  _globals['_EXTRACTIPARESPONSE']._serialized_start=478
  _globals['_EXTRACTIPARESPONSE']._serialized_end=528
  _globals['_PARSERSERVICE']._serialized_start=531
  _globals['_PARSERSERVICE']._serialized_end=797
# @@protoc_insertion_point(module_scope)
