requires 'perl', '5.038000';

# Core dependencies
requires 'Lingua::IPA', '0.05';
requires 'Unicode::Normalize';
requires 'Text::Unidecode';
requires 'utf8::all';

# Network & Protocol
requires 'JSON::PP';
requires 'IO::Socket::INET';

# Development
on 'test' => sub {
    requires 'Test::More';
    requires 'Test::Exception';
    requires 'Test::Deep';
};

